export default [
  { value: "0", label: "Wheat Gluten", abbreviation: "WG" },
  { value: "14", label: "Rye Gluten", abbreviation: "RG" },
  { value: "15", label: "Barley Gluten", abbreviation: "BG" },
  { value: "16", label: "Oat Gluten", abbreviation: "OG" },
  { value: "1", label: "Crustaceans", abbreviation: "C" },
  { value: "2", label: "Eggs", abbreviation: "E" },
  { value: "3", label: "Fish", abbreviation: "F" },
  { value: "5", label: "Soybeans", abbreviation: "S" },
  { value: "6", label: "Milk", abbreviation: "MK" },
  { value: "4", label: "Peanuts", abbreviation: "PN" },
  { value: "7", label: "Walnuts", abbreviation: "WN" },
  { value: "18", label: "Almonds", abbreviation: "AN" },
  { value: "19", label: "Hazelnuts", abbreviation: "HN" },
  { value: "20", label: "Cashew Nuts", abbreviation: "CN" },
  { value: "21", label: "Pecan Nuts", abbreviation: "PNN" },
  { value: "22", label: "Brazilian nuts", abbreviation: "BN" },
  { value: "23", label: "Pistachio Nuts", abbreviation: "PON" },
  { value: "24", label: "Macedonian Nuts", abbreviation: "MN" },
  { value: "8", label: "Celery", abbreviation: "CY" },
  { value: "9", label: "Mustard", abbreviation: "MD" },
  { value: "10", label: "Sesame Seeds", abbreviation: "SS" },
  { value: "11", label: "Sulphites", abbreviation: "SP" },
  { value: "12", label: "Lupin", abbreviation: "L" },
  { value: "13", label: "Molluscs", abbreviation: "M" }
];
